### ISSUE TITLE
Action takes hours to complete

### ISSUE THREAD

**Issue by ericdallo** [nnichols/clojure-dependency-update-action#15]
# Bug Report

## Describe the Bug

The bump action takes more than 2 hours to complete on clojure-lsp repo, [example](https://github.com/clojure-lsp/clojure-lsp/actions/runs/3075253466/jobs/4968513439)
This makes github delays to spawn some other actions as clojure-lsp has lot of actions on a free tier

### Expected Behavior

Expect to take way less time to avoid multiple running tasks from different commits on master.

**Comment by ericdallo** [comment]
c/c @nnichols

**Comment by nnichols** [comment]
This appears to be running in a normal allotment of time across the repositories I've checked. I believe a combination of eliminating GH action checks, caching the loaded dependencies, and stability enhancements to clojars have brought things back to a normal level. Please let me know if it occurs again!
