### ISSUE TITLE
Batch bump PR feature

### ISSUE THREAD

**Issue by ericdallo** [nnichols/clojure-dependency-update-action#3]
# Feature Request

Hi, thanks for the amazing github action, I added it to [clojure-lsp](https://github.com/clojure-lsp/clojure-lsp) and it worked very well!
One feature that would be nice is to generate the PR with all the bumps instead of one by bump, a option like `batch: true` would be great.

**Comment by nnichols** [comment]
Glad to hear it worked!

(For implementation / Note to Self)
I think in the instance that `batch` is set to `true`, that the only other thing that'll need to change with the above is the branch naming convention (In the case that branches aren't being cleaned up after merging for the repository in question). I'm assuming something like `dependencies/clojure/${DATE}` will be fine for most consumers

**Comment by nnichols** [comment]
@ericdallo This has been implemented as of tag v3!

**Comment by ericdallo** [comment]
Cool, I'll update it, thank you !!
