### ISSUE TITLE
Add lib Changelog to the PR feature

### ISSUE THREAD

**Issue by ericdallo** [nnichols/clojure-dependency-update-action#4]
# Feature Request
I known this is not simple but if the lib has a CHANGELOG file on it's repo (if it's a github repo or something like that), add the changelog to the PR description would be great

**Comment by nnichols** [comment]
I'll take a bit to think through this one. I don't think it'll be too hard to write a generic header and the same info as is in the commit message, but I also suspect this would be best implemented with some configurable options around the CHANGELOG message.

**Comment by ericdallo** [comment]
Yeah, at work (Nubank) we have a bot that opens PRs called Bumpito, it's pretty similar to your github action, but it's closed source, unfortunately... 
It opens PRs for our common libs bumps and in the description, it prints something like this:

PR description:
**Bumpito** has found new common libraries versions.

Refer to the following changelogs to see what is new :newspaper_roll:

## Changelogs

<details><summary>common-kafka</summary><p>


## 10.86.0
- Remove jackson-core explicit dependency from common-kafka

## 10.85.1
- remove consumer cron tick code

</p></details>

<details><summary>common-i18n</summary><p>


## 4.5.0
- Fix Federal Holidays for Mexico

</p></details>

<details><summary>common-crypto</summary><p>


## 10.24.1
- improve the way of communicating error getting s3 keys

</p></details>

<details><summary>common-metrics</summary><p>


## 10.6.0
- Add prometheus text format parser

</p></details>

<details><summary>common-redis</summary><p>

Could not parse changelog :(
</p></details>

**Comment by nnichols** [comment]
@ericdallo Following up on this, antq now has the ability to surface links to the GitHub diff between the old and the new version. It's slightly less ergonomic than a compiled list of changelog updates- but it is available for little extra effort. I've updated the commit messages to include these links in this PR: https://github.com/nnichols/clojure-dependency-update-action/pull/9

Would you find these sufficient for now?

**Comment by ericdallo** [comment]
@michols I think worth the shot, better than nothing! thank you

**Comment by nnichols** [comment]
Closed by: https://github.com/nnichols/clojure-dependency-update-action/pull/9
