### ISSUE TITLE
Support monorepo

### ISSUE THREAD

**Issue by ericdallo** [nnichols/clojure-dependency-update-action#7]
# Bug Report

## Describe the Bug
Not sure it's a bug, let me know if I'm wrong.
I love this project and use it all the time on [clojure-lsp](https://github.com/clojure-lsp/clojure-lsp/), the issue is that we moved from a single deps.edn to a modular codebase so now we have this structure:

```
- deps.edn at the root of the project 
|-- cli/deps.edn
|-- lib/deps.edn
```

how could I change this action to check for updates on the 3 deps.edn files? I tried the directories but it didn't work.
Thank you!

**Comment by ericdallo** [comment]
Thank you for the quick reply!
1. yes, on master 😔 
2. sounds great! maybe something simpler like specify the deps.edn files manually would already solve the issue for me

**Comment by nnichols** [comment]
@ericdallo - I have a PR open now to simplify the action's internals (antq now has built-in functionality to do the upgrades, so I'm removing as much of my kludgey use of sed). If you're curious about the changes, here's a link to the PR: https://github.com/nnichols/clojure-dependency-update-action/pull/9 

Would you mind testing this to see if addresses your problem? I've ran a few experiments against a testbed repo and have been able to selectively update child directories- in an admittedly trivial scenario.

You can use this SHA in place of the existing version: `679163d5c8b407342c79a9176d2d559bd1a83e83`

**Comment by ericdallo** [comment]
Sure @michols, I'll change to use it and let you know the next lib version!

**Comment by ericdallo** [comment]
Made the change [here](https://github.com/clojure-lsp/clojure-lsp/commit/0092e726982eae4e57c8f07e09d8231c8c4cf83b)

**Comment by ericdallo** [comment]
@nnichols not sure ,but I think it's in a infinite loop https://github.com/clojure-lsp/clojure-lsp/runs/4992760821?check_suite_focus=true, maybe because my `cli` submodule depends on the `lib` one?

**Comment by ericdallo** [comment]
Oh, not really, it seems that worked :) will keep an eye during this week

**Comment by nnichols** [comment]
Cool! It looks like there's a little overhead inspecting/processing multiple dep files, but it appears to be working as expected

**Comment by nnichols** [comment]
Closed by: https://github.com/nnichols/clojure-dependency-update-action/pull/9
